name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum:

env:
#  The default GIT_AUTHOR_NAME is github.actor
  GIT_AUTHOR_NAME: ${{ github.actor }}
#  The default GIT_AUTHOR_NAME is github.actor@users.noreply.github.com
  GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
  WIKI: wiki
  DOCS: docs

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@master
        with:
          source: ${{ env.DOCS }}
          destination: ${{ env.WIKI }}
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
#          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
#          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          commitMessage: Auto sync ${{ env.DOCS }} to ${{ env.WIKI }} [skip actions]
  
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
          ref: ${{ env.default_branch }}
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@master
        with:
          source: ${{ env.WIKI }}
          destination: ${{ env.DOCS }}
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
#          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
#          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: ${{ env.default_branch }}
          commitMessage: Auto sync ${{ env.WIKI }} to ${{ env.DOCS }} [skip actions]
